import { 
  reinay01, reinay02, reinay03, reinay04,
  moon01, moon02,
  coffee01, coffee02,
  lilith01, lilith02, lilith03
} from "../assets";

export const charactersDatabase = [
  {
    id: 1,
    name: "Reynay Smirov",
    title: "The Lost Mortal",
    category: "Lost Souls",
    element: "Curiosity",
    age: "12 years",
    origin: "Mortal World (displaced to Magical Realm)",
    personality: "Curious, brave, determined",
    abilities: ["Mortal adaptability", "Hidden potential", "Fearless exploration"],
    backstory: "Reynay's story begins when she was disappeared by an evil sorcerer, her mother's ex-boyfriend who sought revenge for being abandoned. Sent to a strange place where humans are scarce and magic is more common than in the world of mere mortals, she was adopted by a pair of wizards who decided to care for her, knowing she was just a mortal. They hid her mortal nature from those around her and chose to live in a forest far from civilization. Reynay never gave up hope for powers or something supernatural to emerge from within her. Her parents didn't know where she came from. Reynay was too curious and more than once she would go out to investigate places where she wasn't allowed to go.",
    description: "A brave 12-year-old girl with an insatiable curiosity and determination that defies her mortal nature. Despite being powerless in a world of magic, her spirit remains unbroken as she searches for her place in this mystical realm.",
    tags: ["fantasy", "oc", "artedigital", "mortal", "lost", "curious"],
    image: reinay01,
    gallery: [reinay01, reinay02, reinay03, reinay04],
  },
  {
    id: 2,
    name: "Moon",
    title: "Guardian of the Night",
    category: "Celestial Beings",
    element: "Lunar",
    age: "Eternal",
    origin: "Celestial Realm",
    personality: "Serene, protective, wise",
    abilities: ["Lunar magic", "Dream guidance", "Night vision", "Tidal control"],
    backstory: "Moon is an ancient celestial guardian who watches over the night and all who dwell within its embrace. Born from the first moonbeam that touched the earth, she guides lost souls through darkness and protects dreamers from nightmares. Her gentle light has been a beacon of hope for countless generations, offering comfort to those who feel alone in the darkness.",
    description: "A luminous figure with pale silver skin that glows softly in darkness. Her long, flowing hair resembles moonbeams, and her eyes hold the depth of starlit skies. She wears ethereal robes that shimmer like moonlight on water.",
    tags: ["celestial", "moon", "guardian", "night", "dreams"],
    image: moon01,
    gallery: [moon01, moon02],
  },
  {
    id: 3,
    name: "Coffee",
    title: "The Energetic Alchemist",
    category: "Modern Mystics",
    element: "Energy",
    age: "22 years",
    origin: "Urban Coffee Shops",
    personality: "Energetic, creative, passionate",
    abilities: ["Energy manipulation", "Potion brewing", "Caffeine magic", "Inspiration casting"],
    backstory: "Coffee discovered her magical abilities while working as a barista in a small, mystical coffee shop. She realized she could infuse emotions and energy into her brews, creating potions that could inspire creativity, boost confidence, or provide comfort. Now she travels between dimensions, bringing the perfect cup to those who need it most, using her magical coffee beans to help people achieve their dreams.",
    description: "A vibrant young woman with warm brown hair streaked with golden highlights that seem to shimmer like coffee beans. Her eyes sparkle with endless energy, and she's always surrounded by the comforting aroma of freshly brewed coffee and magical steam.",
    tags: ["modern", "coffee", "energy", "urban", "alchemy"],
    image: coffee01,
    gallery: [coffee01, coffee02],
  },
  {
    id: 4,
    name: "Lilith",
    title: "The Shadow Weaver",
    category: "Dark Enchantresses",
    element: "Shadow",
    age: "Unknown (appears 25)",
    origin: "The Void Between Worlds",
    personality: "Mysterious, powerful, complex",
    abilities: ["Shadow manipulation", "Void magic", "Dark enchantments", "Reality bending"],
    backstory: "Lilith emerged from the spaces between dimensions, where light and darkness merge into something entirely new. Neither good nor evil, she exists as a force of balance, wielding shadow magic to maintain equilibrium between opposing forces. Her past is shrouded in mystery, but those who encounter her speak of her immense power and the profound wisdom hidden behind her enigmatic smile.",
    description: "A striking figure with raven-black hair and piercing violet eyes that seem to hold secrets of the universe. She wears dark, flowing garments that seem to be woven from shadows themselves, and her presence commands both respect and caution.",
    tags: ["shadow", "mystery", "power", "enchantress", "void"],
    image: lilith01,
    gallery: [lilith01, lilith02, lilith03],
  },
];

export const characterCategories = [
  "All",
  "Lost Souls",
  "Celestial Beings",
  "Modern Mystics",
  "Dark Enchantresses",
];

export const characterElements = [
  "All",
  "Curiosity",
  "Lunar",
  "Energy", 
  "Shadow",
];
