import { carrent, jobit, tripguide, reinay01, reinay02, reinay03, reinay04 } from "../assets";

export const charactersDatabase = [
  {
    id: 1,
    name: "Aria Nightwhisper",
    title: "Guardian of Shadows",
    category: "Ethereal Guardians",
    element: "Shadow",
    age: "Unknown",
    origin: "Shadowlands",
    personality: "Mysterious, protective, wise",
    abilities: ["Shadow manipulation", "Stealth mastery", "Dream walking"],
    backstory: "Aria is an ancient guardian who protects the boundary between dreams and reality. Born from the first shadow cast by moonlight, she has watched over sleeping souls for millennia, ensuring nightmares don't escape into the waking world.",
    description: "A ethereal figure cloaked in shadows and starlight, with silver hair that seems to move like liquid moonbeams. Her eyes hold the depth of endless night skies.",
    tags: ["fantasy", "guardian", "shadow", "ethereal"],
    image: carrent,
    gallery: [carrent, jobit, tripguide],
  },
  {
    id: 2,
    name: "Zex the Techno-Sage",
    title: "Urban Shaman",
    category: "Urban Legends",
    element: "Technology",
    age: "25 (appears)",
    origin: "Neo-Tokyo",
    personality: "Curious, rebellious, innovative",
    abilities: ["Techno-magic", "Code weaving", "Digital divination"],
    backstory: "Once a regular hacker, Zex discovered an ancient spirit living within the city's network infrastructure. Now they blend ancient shamanic practices with cutting-edge technology, serving as a bridge between the digital and spiritual worlds.",
    description: "A young person with cybernetic tattoos that glow with mystic energy, wearing traditional shamanic accessories mixed with futuristic tech gear.",
    tags: ["cyberpunk", "urban", "technology", "shaman"],
    image: jobit,
    gallery: [jobit, carrent, tripguide],
  },
  {
    id: 3,
    name: "Luna Dreamweaver",
    title: "Architect of Dreams",
    category: "Dreamscape Chronicles",
    element: "Dreams",
    age: "Timeless",
    origin: "The Collective Unconscious",
    personality: "Whimsical, empathetic, creative",
    abilities: ["Dream architecture", "Memory manipulation", "Emotion materialization"],
    backstory: "Luna exists in the space between sleeping and waking, crafting beautiful dreamscapes for those who need healing. She can transform nightmares into hope and weave forgotten memories back together.",
    description: "A figure that seems to shift between solid and ethereal, with hair made of stardust and clothes that change color like aurora borealis.",
    tags: ["surreal", "dreams", "healing", "ethereal"],
    image: tripguide,
    gallery: [tripguide, carrent, jobit],
  },
  {
    id: 4,
    name: "Kai Stormheart",
    title: "Thunder's Voice",
    category: "Ethereal Guardians",
    element: "Storm",
    age: "500 years",
    origin: "Sky Citadel",
    personality: "Bold, passionate, loyal",
    abilities: ["Lightning control", "Weather manipulation", "Storm calling"],
    backstory: "Born during the fiercest storm in recorded history, Kai commands the power of thunder and lightning. As a guardian of the skies, they protect travelers from dangerous weather and guide lost souls home.",
    description: "A powerful figure with storm-cloud hair and eyes that flash like lightning. Their presence brings the scent of rain and the rumble of distant thunder.",
    tags: ["fantasy", "storm", "guardian", "elemental"],
    image: carrent,
    gallery: [carrent, jobit, tripguide],
  },
  {
    id: 5,
    name: "Echo the Memory Keeper",
    title: "Historian of Forgotten Tales",
    category: "Urban Legends",
    element: "Memory",
    age: "Ageless",
    origin: "The Old Library",
    personality: "Thoughtful, melancholic, wise",
    abilities: ["Memory reading", "Story preservation", "Time glimpses"],
    backstory: "Echo exists within old libraries and abandoned places, collecting and preserving memories that would otherwise be lost. They can read the history of objects and places through touch.",
    description: "A figure that appears translucent, with books and scrolls floating around them. Their form seems to be made of shifting text and fading photographs.",
    tags: ["urban", "memory", "mystery", "preservation"],
    image: jobit,
    gallery: [jobit, tripguide, carrent],
  },
  {
    id: 6,
    name: "Cosmos the Star Child",
    title: "Guardian of Wonder",
    category: "Dreamscape Chronicles",
    element: "Stars",
    age: "Born yesterday, ancient as the universe",
    origin: "The Space Between Dreams",
    personality: "Innocent, curious, powerful",
    abilities: ["Cosmic manipulation", "Reality bending", "Pure creation"],
    backstory: "Cosmos is the embodiment of childlike wonder and infinite possibility. They exist in dreams where anything can happen, reminding dreamers that magic is real if you believe strongly enough.",
    description: "A child-like figure whose skin sparkles with galaxies, wearing clothes that look like nebulas. Their presence fills spaces with floating stars and cosmic dust.",
    tags: ["cosmic", "dreams", "wonder", "child"],
    image: tripguide,
    gallery: [tripguide, carrent, jobit],
  },
  {
    id: 7,
    name: "Reynay Smirov",
    title: "The Lost Mortal",
    category: "Lost Souls",
    element: "Curiosity",
    age: "12 years",
    origin: "Mortal World (displaced to Magical Realm)",
    personality: "Curious, brave, determined",
    abilities: ["Mortal adaptability", "Hidden potential", "Fearless exploration"],
    backstory: "Reynay's story begins when she was disappeared by an evil sorcerer, her mother's ex-boyfriend who sought revenge for being abandoned. Sent to a strange place where humans are scarce and magic is more common than in the world of mere mortals, she was adopted by a pair of wizards who decided to care for her, knowing she was just a mortal. They hid her mortal nature from those around her and chose to live in a forest far from civilization. Reynay never gave up hope for powers or something supernatural to emerge from within her. Her parents didn't know where she came from. Reynay was too curious and more than once she would go out to investigate places where she wasn't allowed to go.",
    description: "A brave 12-year-old girl with an insatiable curiosity and determination that defies her mortal nature. Despite being powerless in a world of magic, her spirit remains unbroken as she searches for her place in this mystical realm.",
    tags: ["fantasy", "oc", "artedigital", "mortal", "lost", "curious"],
    image: reinay01,
    gallery: [reinay01, reinay02, reinay03, reinay04],
  },
];

export const characterCategories = [
  "All",
  "Ethereal Guardians",
  "Urban Legends", 
  "Dreamscape Chronicles",
  "Lost Souls",
];

export const characterElements = [
  "All",
  "Shadow",
  "Technology",
  "Dreams",
  "Storm",
  "Memory",
  "Stars",
  "Curiosity",
];
